### ISSUE TITLE
Drone never come back

### ISSUE THREAD

**Issue by Crazyht** [GreyHak/dsp-drone-clearing#1]
I start a new game, after harvesting a few resources manually, my Icarus panel 0/3 drones, I wait few minutes but the counter still on 0/3 :( 

If I try disable your plugin my save game launch but generate an error : 
![image](https://user-images.githubusercontent.com/2828405/108627755-82c72c80-7457-11eb-9502-83d82dcb0aec.png)

**Comment by GreyHak** [comment]
Thank you for the report @Crazyht .

I agree the game shouldn't produce an error when the mod gets disabled.  I'll work on fixing that today.  It will mean that clearing tasks won't be saved, but I think that's a reasonable compromise to avoid this error.

Even in the unmodded game it's possible to fly away from your drones so the count stays at zero.  So I chose not to override that mechanic.  With clearing always on this problem is definitely emphasized.  I can look into adding a method to recover lost drones.

**Comment by GreyHak** [comment]
@Crazyht I never saw it during testing before, but I did when I loaded my game today.  A drone got stuck on its task.  I'll resolve this today.  Thank you again for the feedback.

**Comment by GreyHak** [comment]
The drone loss is occurs when Icarus clears an object that a drone has been tasked to clear.

**Comment by Crazyht** [comment]
@GreyHak yes I think that happens when the drone and Icarus try to get the same resource, maybe one hotkey to disable temporarily your mod should be a good idea, it's easy to go out of range of the drone when you move on the planet and sometime I just don't want my drone to get resource when I only move from one building to another :)

**Comment by thezak48** [comment]
I second the idea of a hotkey to disable/enable the mod in game

**Comment by GreyHak** [comment]
Drone lock-up fixed in GitHub.  Will release to thunderstore today.
I would like a method to enable/disable clearing in game, but I need to learn how to do this.  So it's on the list of feature enhancements.

**Comment by thezak48** [comment]
As long as it is on the table to be done then I am happy about it

**Comment by GreyHak** [comment]
Error message after removing the mod should now be fixed in GitHub.

I have confirmed that drones will by default catch up to Icarus in a not-unreasonable amount of time, even after a warp to another star.  So now that the drone-lock-up issue is resolved, drone returns shouldn't be a problem.  (I believe when you switch star systems the drone appears in the new star system in the same location it was in in the old star system.  Drones do not move when you're not on or around a planet.)

I am going to push a release for these two bug fixes so I can close this issue.  Then I'll look into a mechanism to enable/disable clearing in-game.

**Comment by Crazyht** [comment]
Nice thanks

**Comment by GreyHak** [comment]
Version 1.1.0 released.
