### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Dawzzy42** [GreyHak/dsp-drone-clearing#12]
I installed this mod and started getting unhandled exception when placing buildings. Miner specifically, 0.6.17.5932 is my DSP version. Also, drones brought me some carbon nanotubes from a tree I think. Never got those from trees, or anything on starting planet. Reloaded, and same exception each time I dropped the miner. Disabled your mod and no problem with dropping miner.

**Comment by GreyHak** [comment]
@Dawzzy42 Thank you for the report.  I am unable to reproduce your issue.  Please confirm that you are using the latest v1.2.13 release of this mod.  If you're on the latest release of the mod, and the problem is still occurring, please attach a screenshot of the exception message, and your BepInEx LogOutput.log.  If you can help me to reproduce your problem, I'll fix it.

**Comment by Dawzzy42** [comment]
After re-enabling the mod and even starting a new game all-over again, I too was unable to reproduce the error. If it comes up again I will grab a screenshot of the error.
