### ISSUE TITLE
Enhancement Suggestion: Allow clearing while blueprint ghosts are waiting for items.

### ISSUE THREAD

**Issue by w-gates** [GreyHak/dsp-drone-clearing#26]
When you place a blueprint, and some items are not available, a ghost is placed until you get the needed items and return to place the missing items. While the ghosts are there, it blocks the drone clearing.

I recently created new early game blueprints that contain spray coaters and was planning on just leaving the ghosts until I unlocked them but early game is also when I use this mod so I had to delete the ghosts for now.

**Comment by GreyHak** [comment]
JackPS9 on Discord is getting:
229 tasked done count made up of 0 assigned and 229 unassigned drones.
Skipping due to number of drone assignments: totalDroneTaskingCount=229, ConfigEntry'1, droneCount=9, idleDroneCount=9

"Which those tasks would be from a blueprint on the other side of the planet and I dont have all of the items.  Which still makes look like the clearing should be happening. 
Robbie"

**Comment by GreyHak** [comment]
@w-gates, can you test v2.0.0 with blueprints?

**Comment by w-gates** [comment]
> @w-gates, can you test v2.0.0 with blueprints?

Test successful. The drone clearing now happens when there are blueprint ghosts present. Thank you.
