### ISSUE TITLE
Game will not start with this mod enabled

### ISSUE THREAD

**Issue by Sortileger** [GreyHak/dsp-drone-clearing#3]
Installed rodman, bepinex and this mod.  Game will not start past "Loading almost there".  As soon as I disable this mod, game starts fine.  Please let me know if you can help or what I can do to help.  Ver 1.2.1

```
﻿[Message:   BepInEx] BepInEx 5.4.5.0 - DSPGAME
[Info   :   BepInEx] Running under Unity v2018.4.12.5889476
[Info   :   BepInEx] CLR runtime version: 2.0.50727.1433
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [DSP Drone Clearing 1.2.1.0]
[Info   :DSP Drone Clearing] Initialization complete.
[Message:   BepInEx] Chainloader startup complete

```

**Comment by GreyHak** [comment]
Thank you for the bug report @Sortileger.  I've reproduced the problem, and fixed it.  The issue happens when you're loading the mod for the first time and the config file doesn't exist.  The bug went in yesterday when I added the config reloading functionality.  Release v1.2.2 should fix the problem.  Please let me know if you're still having issues.  I greatly appreciate the feedback.  Now I know to test without a config file.
