### ISSUE TITLE
Suggestion:  Realistic resource gathering speed.

### ISSUE THREAD

**Issue by NuclearToasted** [GreyHak/dsp-drone-clearing#7]
I love this mod, thank you for making it.   I think it would be awesome if there was an option for realistic gathering speed... .currently it is amazing, and fast.    

However it currently feels like it's too easy to clear resources.   I would love it if the drones had to spend just as much time as Icarus does clearing the various objects.   Don't get me wrong, this is the best, and my OCD thanks you!! but I would love to see it gather a bit slower.  :)
thank you again for a great mod!

**Comment by GreyHak** [comment]
@NuclearToasted The drones should already be gathering at the same rate Icarus does in the current release.  Perhaps it just looks faster because there are so many drones working at the same time.  I'm happy to add a scale factor to slow them down.  But tell me, now that I've told you the drones should be working at the same rate Icarus does, does it still look like they're too fast?  I'd like your opinion because I would consider that a bug.  Thank you.

**Comment by GreyHak** [comment]
The drones do appear to mine too fast.  The calculations appear the same as the Icarus mining.  Looking into it.
The enhancement to slow the drones down has been pushed to GitHub.

**Comment by GreyHak** [comment]
The GameTick for PlanetFactory (used for drones) is 4 times faster than the GameTick for PlayerAction_Mine (used by Icarus).

**Comment by GreyHak** [comment]
Correct: The GameTick for PlanetFactory (used for drones) is dynamic.  It ranges from 1 to 4 times faster than the GameTick for PlayerAction_Mine (used by Icarus).

**Comment by GreyHak** [comment]
@NuclearToasted Drone speed enhancement and bug fix completed in release v1.2.8.
